apiVersion: v1
data:
  server.yaml: |
    always_allow:
        - resolve-library-id
        - get-library-docs
    categories:
        - docs
    description: Library documentation retrieval
    name: context7
    timeout: 90
kind: ConfigMap
metadata:
  labels:
    app: context7
    component: mcp-server
  name: context7-config
