apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-mgmt
    component: mcp-server
  name: mcp-server-mgmt
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: server-mgmt
  type: ClusterIP
