# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

# This is required for newer versions of golangci-lint
# The error "unsupported version of the configuration: """ means it expects a version field.
# Version 2 is the current standard.
version: 2


linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/crb2nu/loom
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: cmd/
      linters:
        - gochecknoinits

run:
  timeout: 5m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  modules-download-mode: readonly
