apiVersion: v1
kind: Service
metadata:
  labels:
    app: sequentialthinking
    component: mcp-server
  name: mcp-sequentialthinking
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sequentialthinking
  type: ClusterIP
