apiVersion: v1
kind: Service
metadata:
  labels:
    app: office
    component: mcp-server
  name: mcp-office
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: office
  type: ClusterIP
