// generator_instructions.go contains composite instructions file generation and shared helpers.
package skills

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// generateInstructionsFile assembles instructions.md (or GEMINI.md for Gemini) from all instruction-type skills for a platform.
func (g *Generator) generateInstructionsFile(target string, skills []*Skill, bundleSkills []*Skill) ([]string, error) {
	baseDir := g.resolveTargetDir(target)
	if baseDir == "" {
		return nil, nil
	}

	filename := "instructions.md"
	if target == "gemini" {
		filename = "GEMINI.md"
	}

	if g.Verbose {
		fmt.Printf("Generating %s %s from %d skills\n", target, filename, len(skills))
	}

	if g.DryRun {
		fmt.Printf("[dry-run] Would create %s/%s from %d skills\n", baseDir, filename, len(skills))
		return []string{filename}, nil
	}

	if err := os.MkdirAll(baseDir, 0755); err != nil {
		return nil, fmt.Errorf("create dir: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("<!-- Generated by loom from skills-registry.yaml. Do not edit manually. -->\n")
	sb.WriteString("<!-- To customize, add content to _custom_instructions.md -->\n")
	sb.WriteString("# Agent Instructions\n\n")

	for _, skill := range skills {
		title := toTitleCase(skill.Name)
		sb.WriteString(fmt.Sprintf("## %s\n\n", title))

		sourceSkillDir := filepath.Join(g.SourceDir, skill.Name)
		instructions := skill.ResolveInstructions(target, g.CodexHome, sourceSkillDir)
		instructions = stripFirstHeader(instructions)
		sb.WriteString(strings.TrimSpace(instructions))
		sb.WriteString("\n\n")
	}

	if section := g.generateAvailableSkillsSection(target, bundleSkills); section != "" {
		sb.WriteString(section)
		sb.WriteString("\n")
	}

	// Append custom instructions sidecar if it exists
	customPath := filepath.Join(baseDir, "_custom_instructions.md")
	if data, err := os.ReadFile(customPath); err == nil {
		sb.WriteString("<!-- Custom instructions appended below -->\n")
		sb.WriteString(string(data))
		sb.WriteString("\n")
	}

	outputPath := filepath.Join(baseDir, filename)
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return nil, fmt.Errorf("write %s: %w", filename, err)
	}

	return []string{filename}, nil
}

func (g *Generator) generateAvailableSkillsSection(target string, skills []*Skill) string {
	basePath := g.skillHomePath(target)
	if basePath == "" {
		return ""
	}

	entries := g.availableSkillEntries(basePath, skills)
	if len(entries) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString("## Skills\n")
	sb.WriteString("A skill is a set of local instructions stored in a `SKILL.md` file.\n")
	sb.WriteString("Below is the list of skills available in this environment.\n")
	sb.WriteString("### Available skills\n")

	for _, entry := range entries {
		sb.WriteString(fmt.Sprintf("- %s: %s (file: %s)\n", entry.Name, entry.Description, entry.Path))
	}

	sb.WriteString("### How to use skills\n")
	sb.WriteString("- Discovery: The list above is the skills available in this session. Skill bodies live at the listed paths.\n")
	sb.WriteString("- Trigger rules: If the user names a skill or the task clearly matches one, use it for that turn.\n")
	sb.WriteString("- How to use a skill: Open its `SKILL.md`, read only what you need, and prefer bundled `scripts/`, `references/`, and `assets/` over re-creating content.\n")
	sb.WriteString("- Safety and fallback: If a skill is missing or blocked, say so briefly and continue with the best fallback.\n")

	return sb.String()
}

type availableSkillEntry struct {
	Name        string
	Description string
	Path        string
}

func (g *Generator) availableSkillEntries(basePath string, skills []*Skill) []availableSkillEntry {
	seen := make(map[string]bool)
	entries := make([]availableSkillEntry, 0, len(skills))

	addEntry := func(name, desc, skillPath string) {
		name = strings.TrimSpace(name)
		desc = strings.Join(strings.Fields(strings.TrimSpace(desc)), " ")
		skillPath = strings.TrimSpace(skillPath)
		if name == "" || desc == "" || skillPath == "" || seen[name] {
			return
		}
		seen[name] = true
		entries = append(entries, availableSkillEntry{
			Name:        name,
			Description: desc,
			Path:        skillPath,
		})
	}

	for _, skill := range skills {
		if skill == nil || skill.Common == nil {
			continue
		}
		addEntry(skill.Name, skill.Common.Description, filepath.Join(basePath, skill.Name, "SKILL.md"))
	}

	diskEntries, _ := discoverSkillEntries(basePath)
	sort.SliceStable(diskEntries, func(i, j int) bool {
		return diskEntries[i].Name < diskEntries[j].Name
	})
	for _, entry := range diskEntries {
		addEntry(entry.Name, entry.Description, entry.Path)
	}

	return entries
}

func discoverSkillEntries(basePath string) ([]availableSkillEntry, error) {
	entries := make([]availableSkillEntry, 0)
	err := filepath.Walk(basePath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info == nil || info.IsDir() || info.Name() != "SKILL.md" {
			return nil
		}

		name, desc, ok := readSkillFrontmatter(path)
		if !ok {
			return nil
		}
		entries = append(entries, availableSkillEntry{
			Name:        name,
			Description: desc,
			Path:        path,
		})
		return nil
	})
	return entries, err
}

func readSkillFrontmatter(path string) (name string, desc string, ok bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", "", false
	}

	text := string(data)
	if !strings.HasPrefix(text, "---\n") {
		return "", "", false
	}
	rest := text[len("---\n"):]
	end := strings.Index(rest, "\n---")
	if end < 0 {
		return "", "", false
	}

	var shortDesc string
	for _, rawLine := range strings.Split(rest[:end], "\n") {
		line := strings.TrimSpace(rawLine)
		switch {
		case strings.HasPrefix(line, "name:"):
			name = parseSkillFrontmatterValue(strings.TrimSpace(strings.TrimPrefix(line, "name:")))
		case strings.HasPrefix(line, "description:"):
			desc = parseSkillFrontmatterValue(strings.TrimSpace(strings.TrimPrefix(line, "description:")))
		case strings.HasPrefix(line, "short-description:"):
			shortDesc = parseSkillFrontmatterValue(strings.TrimSpace(strings.TrimPrefix(line, "short-description:")))
		}
	}

	if shortDesc != "" {
		desc = shortDesc
	}
	name = strings.TrimSpace(name)
	desc = strings.Join(strings.Fields(strings.TrimSpace(desc)), " ")
	return name, desc, name != "" && desc != ""
}

func parseSkillFrontmatterValue(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return ""
	}
	if unquoted, err := strconv.Unquote(raw); err == nil {
		return unquoted
	}
	return strings.Trim(raw, `"'`)
}

func (g *Generator) skillHomePath(target string) string {
	switch target {
	case "codex":
		if g.CodexSkillsDir != "" {
			return g.CodexSkillsDir
		}
		if g.CodexHome != "" {
			return filepath.Join(g.CodexHome, "skills")
		}
	case "gemini":
		if strings.TrimSpace(g.GeminiSkillsHome) != "" {
			return strings.TrimRight(g.GeminiSkillsHome, "/")
		}
		home, err := os.UserHomeDir()
		if err == nil && home != "" {
			return filepath.Join(home, ".gemini", "skills")
		}
	}
	return ""
}

// sortSkillsByPriority sorts skills by explicit Priority (lower first).
// Skills without a Priority come after explicitly prioritized ones.
// Registry order is preserved among skills with equal or missing priority (stable sort).
func sortSkillsByPriority(skills []*Skill) {
	sort.SliceStable(skills, func(i, j int) bool {
		pi := skills[i].Priority
		pj := skills[j].Priority
		if pi == nil && pj == nil {
			return false // preserve registry order
		}
		if pi == nil {
			return false // nil sorts after explicit
		}
		if pj == nil {
			return true // explicit sorts before nil
		}
		return *pi < *pj
	})
}

// stripFirstHeader removes the first # header and any immediately following blank lines.
func stripFirstHeader(instructions string) string {
	lines := strings.Split(instructions, "\n")
	startIdx := 0
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "# ") {
			startIdx = i + 1
			break
		}
	}

	// Skip blank lines after header
	for startIdx < len(lines) && strings.TrimSpace(lines[startIdx]) == "" {
		startIdx++
	}

	if startIdx > 0 && startIdx < len(lines) {
		return strings.Join(lines[startIdx:], "\n")
	}
	return instructions
}

// escapeYAMLString escapes a string for use as a YAML double-quoted scalar value.
func escapeYAMLString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

// copyFile copies a file from src to dst.
func copyFile(src, dst string) error {
	sourceFile, err := os.Open(src)
	if err != nil {
		return err
	}
	defer sourceFile.Close()

	// Ensure parent directory exists
	if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
		return err
	}

	destFile, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer destFile.Close()

	_, err = io.Copy(destFile, sourceFile)
	if err != nil {
		return err
	}

	// Preserve executable bit
	info, err := sourceFile.Stat()
	if err != nil {
		return err
	}
	return os.Chmod(dst, info.Mode())
}

// toTitleCase converts kebab-case to Title Case.
func toTitleCase(s string) string {
	words := strings.Split(s, "-")
	for i, word := range words {
		if len(word) > 0 {
			words[i] = strings.ToUpper(word[:1]) + word[1:]
		}
	}
	return strings.Join(words, " ")
}

func shortSkillDescription(desc string) string {
	desc = strings.TrimSpace(strings.Join(strings.Fields(desc), " "))
	if desc == "" {
		return ""
	}

	for _, sep := range []string{". ", "! ", "? "} {
		if idx := strings.Index(desc, sep); idx > 0 {
			return strutilTrim(desc[:idx+1], 120)
		}
	}

	return strutilTrim(desc, 120)
}

func strutilTrim(s string, max int) string {
	if max <= 0 || len(s) <= max {
		return s
	}
	if max <= 3 {
		return s[:max]
	}
	return strings.TrimSpace(s[:max-3]) + "..."
}
