package hud

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

//go:embed loom-vibrancy.glsl
var shaderSource string

// shaderInstallPath returns the destination path for the shader file.
func shaderInstallPath() string {
	if home, err := os.UserHomeDir(); err == nil && home != "" {
		return filepath.Join(home, ".config", "loom", "loom-vibrancy.glsl")
	}
	if cfg, err := os.UserConfigDir(); err == nil && cfg != "" {
		return filepath.Join(cfg, "loom", "loom-vibrancy.glsl")
	}
	return filepath.Join(".", "loom-vibrancy.glsl")
}

// InstallShader copies the embedded loom-vibrancy.glsl shader to
// ~/.config/loom/loom-vibrancy.glsl, creating parent directories as needed.
func InstallShader() error {
	dest := shaderInstallPath()
	if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
		return fmt.Errorf("create shader directory: %w", err)
	}
	if err := os.WriteFile(dest, []byte(shaderSource), 0644); err != nil {
		return fmt.Errorf("write shader: %w", err)
	}
	fmt.Printf("Shader installed: %s\n", dest)
	return nil
}

// GenerateGhosttyConfig writes a complete Ghostty config snippet to stdout
// that configures the deep teal HUD palette, quick terminal, keybind, and shader.
func GenerateGhosttyConfig() string {
	shaderPath := shaderInstallPath()

	var b strings.Builder
	b.WriteString("# ─── Loom HUD — Ghostty Configuration ───\n")
	b.WriteString("# Generated by: loom hud --ghostty-config\n")
	b.WriteString("# Append to: ~/Library/Application Support/com.mitchellh.ghostty/config\n\n")

	// 16-color palette (Webdevcody riced — matches user's daily-use Ghostty config).
	b.WriteString("# ── Palette: Webdevcody Riced ──\n")
	b.WriteString("palette = 0=#001315\n")  // black (bg-primary)
	b.WriteString("palette = 1=#E61E3F\n")  // red (error)
	b.WriteString("palette = 2=#60E66F\n")  // green (success)
	b.WriteString("palette = 3=#F1D868\n")  // yellow (warning)
	b.WriteString("palette = 4=#018799\n")  // blue (info)
	b.WriteString("palette = 5=#F75F94\n")  // magenta (accent-pink)
	b.WriteString("palette = 6=#82F0FF\n")  // cyan (fg-secondary)
	b.WriteString("palette = 7=#81F0FE\n")  // white (fg-primary)
	b.WriteString("palette = 8=#002227\n")  // bright black (border)
	b.WriteString("palette = 9=#E95D74\n")  // bright red (accent)
	b.WriteString("palette = 10=#60E66F\n") // bright green
	b.WriteString("palette = 11=#E3946A\n") // bright yellow (warm)
	b.WriteString("palette = 12=#018799\n") // bright blue
	b.WriteString("palette = 13=#F75F94\n") // bright magenta
	b.WriteString("palette = 14=#82F0FF\n") // bright cyan
	b.WriteString("palette = 15=#C7F9FF\n") // bright white
	b.WriteString("background = #001315\n")
	b.WriteString("foreground = #81F0FE\n")
	b.WriteString("cursor-color = #82F0FF\n")
	b.WriteString("selection-background = #00343A\n")
	b.WriteString("selection-foreground = #81F0FE\n\n")

	// Quick terminal settings (right-side HUD sidebar).
	b.WriteString("# ── Quick Terminal (HUD sidebar) ──\n")
	b.WriteString("quick-terminal-position = right\n")
	b.WriteString("quick-terminal-size = 380\n")
	b.WriteString("quick-terminal-animation-duration = 0.15\n")
	b.WriteString("quick-terminal-shell-integration = none\n")
	b.WriteString(fmt.Sprintf("quick-terminal-command = %s\n\n", strconv.Quote("loom hud --tui")))

	// Global keybind for quick terminal toggle.
	b.WriteString("# ── Global Keybind ──\n")
	b.WriteString("keybind = global:cmd+shift+l=toggle_quick_terminal\n\n")

	// Shader.
	b.WriteString("# ── Custom Shader ──\n")
	b.WriteString("# Install first: loom hud --install-shader\n")
	b.WriteString(fmt.Sprintf("custom-shader = %s\n\n", strconv.Quote(shaderPath)))

	// Font and appearance recommendations.
	b.WriteString("# ── Recommended Appearance ──\n")
	b.WriteString("# font-family = JetBrains Mono\n")
	b.WriteString("# font-size = 13\n")
	b.WriteString("# background-opacity = 0.92\n")
	b.WriteString("# window-padding-x = 8\n")
	b.WriteString("# window-padding-y = 4\n")
	b.WriteString("# window-decoration = false\n")

	return b.String()
}
