package hud

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

//go:embed loom-vibrancy.glsl
var shaderSource string

// shaderInstallPath returns the destination path for the shader file.
func shaderInstallPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "loom", "loom-vibrancy.glsl")
}

// InstallShader copies the embedded loom-vibrancy.glsl shader to
// ~/.config/loom/loom-vibrancy.glsl, creating parent directories as needed.
func InstallShader() error {
	dest := shaderInstallPath()
	if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
		return fmt.Errorf("create shader directory: %w", err)
	}
	if err := os.WriteFile(dest, []byte(shaderSource), 0644); err != nil {
		return fmt.Errorf("write shader: %w", err)
	}
	fmt.Printf("Shader installed: %s\n", dest)
	return nil
}

// GenerateGhosttyConfig writes a complete Ghostty config snippet to stdout
// that configures the deep teal HUD palette, quick terminal, keybind, and shader.
func GenerateGhosttyConfig() string {
	shaderPath := shaderInstallPath()

	var b strings.Builder
	b.WriteString("# ─── Loom HUD — Ghostty Configuration ───\n")
	b.WriteString("# Generated by: loom hud --ghostty-config\n")
	b.WriteString("# Append to: ~/Library/Application Support/com.mitchellh.ghostty/config\n\n")

	// 16-color palette (deep teal theme).
	b.WriteString("# ── Palette: Deep Teal ──\n")
	b.WriteString("palette = 0=#00171A\n")  // black (bg-primary)
	b.WriteString("palette = 1=#E61E3F\n")  // red (error)
	b.WriteString("palette = 2=#22B255\n")  // green (success)
	b.WriteString("palette = 3=#E7B312\n")  // yellow (warning)
	b.WriteString("palette = 4=#018799\n")  // blue (info)
	b.WriteString("palette = 5=#9B5CD0\n")  // magenta (tier-short)
	b.WriteString("palette = 6=#5EBDC9\n")  // cyan (fg-secondary)
	b.WriteString("palette = 7=#81F0FE\n")  // white (fg-primary / bright cyan)
	b.WriteString("palette = 8=#035964\n")  // bright black (border)
	b.WriteString("palette = 9=#E95D74\n")  // bright red (accent)
	b.WriteString("palette = 10=#4EEAFE\n") // bright green (tier-working)
	b.WriteString("palette = 11=#F0D560\n") // bright yellow
	b.WriteString("palette = 12=#2A7A87\n") // bright blue (fg-muted)
	b.WriteString("palette = 13=#E95D74\n") // bright magenta (accent)
	b.WriteString("palette = 14=#81F0FE\n") // bright cyan (fg-primary)
	b.WriteString("palette = 15=#C0FCFF\n") // bright white
	b.WriteString("background = #00171A\n")
	b.WriteString("foreground = #81F0FE\n")
	b.WriteString("cursor-color = #E95D74\n")
	b.WriteString("selection-background = #035964\n")
	b.WriteString("selection-foreground = #81F0FE\n\n")

	// Quick terminal settings (right-side HUD sidebar).
	b.WriteString("# ── Quick Terminal (HUD sidebar) ──\n")
	b.WriteString("quick-terminal-position = right\n")
	b.WriteString("quick-terminal-size = 380\n")
	b.WriteString("quick-terminal-animation-duration = 0.15\n\n")

	// Global keybind for quick terminal toggle.
	b.WriteString("# ── Global Keybind ──\n")
	b.WriteString("keybind = global:cmd+shift+l=toggle_quick_terminal\n\n")

	// Shader.
	b.WriteString("# ── Custom Shader ──\n")
	b.WriteString("# Install first: loom hud --install-shader\n")
	b.WriteString(fmt.Sprintf("custom-shader = %s\n\n", shaderPath))

	// Font and appearance recommendations.
	b.WriteString("# ── Recommended Appearance ──\n")
	b.WriteString("# font-family = JetBrains Mono\n")
	b.WriteString("# font-size = 13\n")
	b.WriteString("# background-opacity = 0.92\n")
	b.WriteString("# window-padding-x = 8\n")
	b.WriteString("# window-padding-y = 4\n")
	b.WriteString("# window-decoration = false\n")

	return b.String()
}
