apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-apps-k3s
    component: mcp-server
  name: mcp-k8s-apps-k3s
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8s-apps-k3s
  type: ClusterIP
