---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ai.flexinfer
  resources:
  - clusters
  - federatedmodels
  - gpugroups
  - loraadapters
  - modelcaches
  - modelcatalogs
  - modeldeployments
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.flexinfer
  resources:
  - clusters/finalizers
  - federatedmodels/finalizers
  - gpugroups/finalizers
  - loraadapters/finalizers
  - modelcaches/finalizers
  - modeldeployments/finalizers
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - ai.flexinfer
  resources:
  - clusters/status
  - federatedmodels/status
  - gpugroups/status
  - gpuprofiles/status
  - loraadapters/status
  - modelcaches/status
  - modelcatalogs/status
  - modeldeployments/status
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ai.flexinfer
  resources:
  - gpuprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
