---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.flexinfer
  resources:
  - clusters
  - federatedmodels
  - gpuleases
  - loraadapters
  - modelbackfills
  - modelcaches
  - modelcatalogs
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.flexinfer
  resources:
  - clusters/finalizers
  - federatedmodels/finalizers
  - loraadapters/finalizers
  - modelbackfills/finalizers
  - modelcaches/finalizers
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - ai.flexinfer
  resources:
  - clusters/status
  - federatedmodels/status
  - gpuleases/status
  - gpuprofiles/status
  - loraadapters/status
  - modelbackfills/status
  - modelcaches/status
  - modelcatalogs/status
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ai.flexinfer
  resources:
  - gamingsessions
  - gpuprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ai.flexinfer.ai
  resources:
  - gamingsessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.flexinfer.ai
  resources:
  - gamingsessions/finalizers
  verbs:
  - update
- apiGroups:
  - ai.flexinfer.ai
  resources:
  - gamingsessions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
