apiVersion: v1
kind: Service
metadata:
  labels:
    app: time
    component: mcp-server
  name: mcp-time
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: time
  type: ClusterIP
