apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    component: mcp-server
  name: mcp-minio
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: minio
  type: ClusterIP
