apiVersion: v1
kind: Service
metadata:
  labels:
    app: flux
    component: mcp-server
  name: mcp-flux
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: flux
  type: ClusterIP
