//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AbliterationSpec) DeepCopyInto(out *AbliterationSpec) {
	*out = *in
	if in.TargetLayers != nil {
		in, out := &in.TargetLayers, &out.TargetLayers
		*out = new(string)
		**out = **in
	}
	if in.WeightMatrices != nil {
		in, out := &in.WeightMatrices, &out.WeightMatrices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NumSamples != nil {
		in, out := &in.NumSamples, &out.NumSamples
		*out = new(int32)
		**out = **in
	}
	if in.MaxMemoryGB != nil {
		in, out := &in.MaxMemoryGB, &out.MaxMemoryGB
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.SkipVisionLayers != nil {
		in, out := &in.SkipVisionLayers, &out.SkipVisionLayers
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AbliterationSpec.
func (in *AbliterationSpec) DeepCopy() *AbliterationSpec {
	if in == nil {
		return nil
	}
	out := new(AbliterationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AbliterationStatus) DeepCopyInto(out *AbliterationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AbliterationStatus.
func (in *AbliterationStatus) DeepCopy() *AbliterationStatus {
	if in == nil {
		return nil
	}
	out := new(AbliterationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntiThrashingConfig) DeepCopyInto(out *AntiThrashingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntiThrashingConfig.
func (in *AntiThrashingConfig) DeepCopy() *AntiThrashingConfig {
	if in == nil {
		return nil
	}
	out := new(AntiThrashingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchmarkSpec) DeepCopyInto(out *BenchmarkSpec) {
	*out = *in
	if in.WarmupIterations != nil {
		in, out := &in.WarmupIterations, &out.WarmupIterations
		*out = new(int32)
		**out = **in
	}
	if in.MinDuration != nil {
		in, out := &in.MinDuration, &out.MinDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.Iterations != nil {
		in, out := &in.Iterations, &out.Iterations
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchmarkSpec.
func (in *BenchmarkSpec) DeepCopy() *BenchmarkSpec {
	if in == nil {
		return nil
	}
	out := new(BenchmarkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalibrationSpec) DeepCopyInto(out *CalibrationSpec) {
	*out = *in
	if in.MaxSeqLen != nil {
		in, out := &in.MaxSeqLen, &out.MaxSeqLen
		*out = new(int32)
		**out = **in
	}
	if in.MaxSamples != nil {
		in, out := &in.MaxSamples, &out.MaxSamples
		*out = new(int32)
		**out = **in
	}
	if in.NParallelCalibSamples != nil {
		in, out := &in.NParallelCalibSamples, &out.NParallelCalibSamples
		*out = new(int32)
		**out = **in
	}
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalibrationSpec.
func (in *CalibrationSpec) DeepCopy() *CalibrationSpec {
	if in == nil {
		return nil
	}
	out := new(CalibrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComfyUISpec) DeepCopyInto(out *ComfyUISpec) {
	*out = *in
	if in.PreloadModels != nil {
		in, out := &in.PreloadModels, &out.PreloadModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnableCORS != nil {
		in, out := &in.EnableCORS, &out.EnableCORS
		*out = new(bool)
		**out = **in
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComfyUISpec.
func (in *ComfyUISpec) DeepCopy() *ComfyUISpec {
	if in == nil {
		return nil
	}
	out := new(ComfyUISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadSpec) DeepCopyInto(out *DownloadSpec) {
	*out = *in
	if in.MaxMemoryGB != nil {
		in, out := &in.MaxMemoryGB, &out.MaxMemoryGB
		*out = new(int32)
		**out = **in
	}
	if in.HFTransfer != nil {
		in, out := &in.HFTransfer, &out.HFTransfer
		*out = new(bool)
		**out = **in
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadSpec.
func (in *DownloadSpec) DeepCopy() *DownloadSpec {
	if in == nil {
		return nil
	}
	out := new(DownloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinetuneDatasetSpec) DeepCopyInto(out *FinetuneDatasetSpec) {
	*out = *in
	if in.HuggingFace != nil {
		in, out := &in.HuggingFace, &out.HuggingFace
		*out = new(string)
		**out = **in
	}
	if in.PVCName != nil {
		in, out := &in.PVCName, &out.PVCName
		*out = new(string)
		**out = **in
	}
	if in.PVCSubPath != nil {
		in, out := &in.PVCSubPath, &out.PVCSubPath
		*out = new(string)
		**out = **in
	}
	if in.Split != nil {
		in, out := &in.Split, &out.Split
		*out = new(string)
		**out = **in
	}
	if in.MaxSamples != nil {
		in, out := &in.MaxSamples, &out.MaxSamples
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinetuneDatasetSpec.
func (in *FinetuneDatasetSpec) DeepCopy() *FinetuneDatasetSpec {
	if in == nil {
		return nil
	}
	out := new(FinetuneDatasetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinetuneLoRAConfig) DeepCopyInto(out *FinetuneLoRAConfig) {
	*out = *in
	if in.Rank != nil {
		in, out := &in.Rank, &out.Rank
		*out = new(int32)
		**out = **in
	}
	if in.Alpha != nil {
		in, out := &in.Alpha, &out.Alpha
		*out = new(int32)
		**out = **in
	}
	if in.Dropout != nil {
		in, out := &in.Dropout, &out.Dropout
		*out = new(string)
		**out = **in
	}
	if in.TargetModules != nil {
		in, out := &in.TargetModules, &out.TargetModules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinetuneLoRAConfig.
func (in *FinetuneLoRAConfig) DeepCopy() *FinetuneLoRAConfig {
	if in == nil {
		return nil
	}
	out := new(FinetuneLoRAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinetuneSpec) DeepCopyInto(out *FinetuneSpec) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(FinetuneMode)
		**out = **in
	}
	in.Dataset.DeepCopyInto(&out.Dataset)
	if in.LoRA != nil {
		in, out := &in.LoRA, &out.LoRA
		*out = new(FinetuneLoRAConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Epochs != nil {
		in, out := &in.Epochs, &out.Epochs
		*out = new(int32)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.LearningRate != nil {
		in, out := &in.LearningRate, &out.LearningRate
		*out = new(string)
		**out = **in
	}
	if in.MaxSeqLen != nil {
		in, out := &in.MaxSeqLen, &out.MaxSeqLen
		*out = new(int32)
		**out = **in
	}
	if in.MergeAdapter != nil {
		in, out := &in.MergeAdapter, &out.MergeAdapter
		*out = new(bool)
		**out = **in
	}
	if in.UseGPU != nil {
		in, out := &in.UseGPU, &out.UseGPU
		*out = new(bool)
		**out = **in
	}
	if in.MaxMemoryGB != nil {
		in, out := &in.MaxMemoryGB, &out.MaxMemoryGB
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.GradientCheckpointing != nil {
		in, out := &in.GradientCheckpointing, &out.GradientCheckpointing
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinetuneSpec.
func (in *FinetuneSpec) DeepCopy() *FinetuneSpec {
	if in == nil {
		return nil
	}
	out := new(FinetuneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinetuneStatus) DeepCopyInto(out *FinetuneStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinetuneStatus.
func (in *FinetuneStatus) DeepCopy() *FinetuneStatus {
	if in == nil {
		return nil
	}
	out := new(FinetuneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlashLoaderSpec) DeepCopyInto(out *FlashLoaderSpec) {
	*out = *in
	if in.TmpfsSizeLimit != nil {
		in, out := &in.TmpfsSizeLimit, &out.TmpfsSizeLimit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlashLoaderSpec.
func (in *FlashLoaderSpec) DeepCopy() *FlashLoaderSpec {
	if in == nil {
		return nil
	}
	out := new(FlashLoaderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUAllocation) DeepCopyInto(out *GPUAllocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUAllocation.
func (in *GPUAllocation) DeepCopy() *GPUAllocation {
	if in == nil {
		return nil
	}
	out := new(GPUAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUGroup) DeepCopyInto(out *GPUGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUGroup.
func (in *GPUGroup) DeepCopy() *GPUGroup {
	if in == nil {
		return nil
	}
	out := new(GPUGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUGroupList) DeepCopyInto(out *GPUGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUGroupList.
func (in *GPUGroupList) DeepCopy() *GPUGroupList {
	if in == nil {
		return nil
	}
	out := new(GPUGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUGroupMember) DeepCopyInto(out *GPUGroupMember) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUGroupMember.
func (in *GPUGroupMember) DeepCopy() *GPUGroupMember {
	if in == nil {
		return nil
	}
	out := new(GPUGroupMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUGroupModelStatus) DeepCopyInto(out *GPUGroupModelStatus) {
	*out = *in
	if in.QueuedSince != nil {
		in, out := &in.QueuedSince, &out.QueuedSince
		*out = (*in).DeepCopy()
	}
	if in.LastActiveTime != nil {
		in, out := &in.LastActiveTime, &out.LastActiveTime
		*out = (*in).DeepCopy()
	}
	if in.PreemptedAt != nil {
		in, out := &in.PreemptedAt, &out.PreemptedAt
		*out = (*in).DeepCopy()
	}
	if in.LastPreemptionResult != nil {
		in, out := &in.LastPreemptionResult, &out.LastPreemptionResult
		*out = new(PreemptionResult)
		(*in).DeepCopyInto(*out)
	}
	if in.QueueHistory != nil {
		in, out := &in.QueueHistory, &out.QueueHistory
		*out = make([]QueueSample, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUGroupModelStatus.
func (in *GPUGroupModelStatus) DeepCopy() *GPUGroupModelStatus {
	if in == nil {
		return nil
	}
	out := new(GPUGroupModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUGroupScalingPolicy) DeepCopyInto(out *GPUGroupScalingPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUGroupScalingPolicy.
func (in *GPUGroupScalingPolicy) DeepCopy() *GPUGroupScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(GPUGroupScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUGroupSpec) DeepCopyInto(out *GPUGroupSpec) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]GPUGroupMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.ScalingPolicy = in.ScalingPolicy
	out.AntiThrashing = in.AntiThrashing
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUGroupSpec.
func (in *GPUGroupSpec) DeepCopy() *GPUGroupSpec {
	if in == nil {
		return nil
	}
	out := new(GPUGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUGroupStatus) DeepCopyInto(out *GPUGroupStatus) {
	*out = *in
	if in.AllocatedGPU != nil {
		in, out := &in.AllocatedGPU, &out.AllocatedGPU
		*out = new(GPUAllocation)
		**out = **in
	}
	if in.LastSwapTime != nil {
		in, out := &in.LastSwapTime, &out.LastSwapTime
		*out = (*in).DeepCopy()
	}
	if in.ModelStatuses != nil {
		in, out := &in.ModelStatuses, &out.ModelStatuses
		*out = make([]GPUGroupModelStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUGroupStatus.
func (in *GPUGroupStatus) DeepCopy() *GPUGroupStatus {
	if in == nil {
		return nil
	}
	out := new(GPUGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMSpec) DeepCopyInto(out *LiteLLMSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMSpec.
func (in *LiteLLMSpec) DeepCopy() *LiteLLMSpec {
	if in == nil {
		return nil
	}
	out := new(LiteLLMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaCppSpec) DeepCopyInto(out *LlamaCppSpec) {
	*out = *in
	if in.ContextSize != nil {
		in, out := &in.ContextSize, &out.ContextSize
		*out = new(int32)
		**out = **in
	}
	if in.NGPULayers != nil {
		in, out := &in.NGPULayers, &out.NGPULayers
		*out = new(int32)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.Threads != nil {
		in, out := &in.Threads, &out.Threads
		*out = new(int32)
		**out = **in
	}
	if in.FlashAttention != nil {
		in, out := &in.FlashAttention, &out.FlashAttention
		*out = new(bool)
		**out = **in
	}
	if in.MainGPU != nil {
		in, out := &in.MainGPU, &out.MainGPU
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaCppSpec.
func (in *LlamaCppSpec) DeepCopy() *LlamaCppSpec {
	if in == nil {
		return nil
	}
	out := new(LlamaCppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLCCompileOptions) DeepCopyInto(out *MLCCompileOptions) {
	*out = *in
	if in.UseCutlass != nil {
		in, out := &in.UseCutlass, &out.UseCutlass
		*out = new(bool)
		**out = **in
	}
	if in.UseFlashInfer != nil {
		in, out := &in.UseFlashInfer, &out.UseFlashInfer
		*out = new(bool)
		**out = **in
	}
	if in.UseCublasGemm != nil {
		in, out := &in.UseCublasGemm, &out.UseCublasGemm
		*out = new(bool)
		**out = **in
	}
	if in.UseCudaGraph != nil {
		in, out := &in.UseCudaGraph, &out.UseCudaGraph
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLCCompileOptions.
func (in *MLCCompileOptions) DeepCopy() *MLCCompileOptions {
	if in == nil {
		return nil
	}
	out := new(MLCCompileOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLCLLMSpec) DeepCopyInto(out *MLCLLMSpec) {
	*out = *in
	if in.GPUMemoryBytes != nil {
		in, out := &in.GPUMemoryBytes, &out.GPUMemoryBytes
		*out = new(int64)
		**out = **in
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(MLCOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.CompileOptions != nil {
		in, out := &in.CompileOptions, &out.CompileOptions
		*out = new(MLCCompileOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLCLLMSpec.
func (in *MLCLLMSpec) DeepCopy() *MLCLLMSpec {
	if in == nil {
		return nil
	}
	out := new(MLCLLMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLCOverrides) DeepCopyInto(out *MLCOverrides) {
	*out = *in
	if in.PrefillChunkSize != nil {
		in, out := &in.PrefillChunkSize, &out.PrefillChunkSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxTotalSeqLength != nil {
		in, out := &in.MaxTotalSeqLength, &out.MaxTotalSeqLength
		*out = new(int32)
		**out = **in
	}
	if in.MaxNumSequence != nil {
		in, out := &in.MaxNumSequence, &out.MaxNumSequence
		*out = new(int32)
		**out = **in
	}
	if in.ContextWindowSize != nil {
		in, out := &in.ContextWindowSize, &out.ContextWindowSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLCOverrides.
func (in *MLCOverrides) DeepCopy() *MLCOverrides {
	if in == nil {
		return nil
	}
	out := new(MLCOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCache) DeepCopyInto(out *ModelCache) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCache.
func (in *ModelCache) DeepCopy() *ModelCache {
	if in == nil {
		return nil
	}
	out := new(ModelCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelCache) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheList) DeepCopyInto(out *ModelCacheList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelCache, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheList.
func (in *ModelCacheList) DeepCopy() *ModelCacheList {
	if in == nil {
		return nil
	}
	out := new(ModelCacheList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelCacheList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheSpec) DeepCopyInto(out *ModelCacheSpec) {
	*out = *in
	if in.ClusterStorageClassName != nil {
		in, out := &in.ClusterStorageClassName, &out.ClusterStorageClassName
		*out = new(string)
		**out = **in
	}
	if in.ExistingClaimName != nil {
		in, out := &in.ExistingClaimName, &out.ExistingClaimName
		*out = new(string)
		**out = **in
	}
	if in.ModelPath != nil {
		in, out := &in.ModelPath, &out.ModelPath
		*out = new(string)
		**out = **in
	}
	if in.StorageSize != nil {
		in, out := &in.StorageSize, &out.StorageSize
		*out = new(string)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(string)
		**out = **in
	}
	if in.OCIRegistrySecretRef != nil {
		in, out := &in.OCIRegistrySecretRef, &out.OCIRegistrySecretRef
		*out = new(string)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HostPath != nil {
		in, out := &in.HostPath, &out.HostPath
		*out = new(string)
		**out = **in
	}
	if in.EvictionThresholdPercent != nil {
		in, out := &in.EvictionThresholdPercent, &out.EvictionThresholdPercent
		*out = new(int32)
		**out = **in
	}
	if in.MaxCacheSizeBytes != nil {
		in, out := &in.MaxCacheSizeBytes, &out.MaxCacheSizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.ModelGroup != nil {
		in, out := &in.ModelGroup, &out.ModelGroup
		*out = new(string)
		**out = **in
	}
	if in.RetentionPriority != nil {
		in, out := &in.RetentionPriority, &out.RetentionPriority
		*out = new(int32)
		**out = **in
	}
	if in.FlashLoader != nil {
		in, out := &in.FlashLoader, &out.FlashLoader
		*out = new(FlashLoaderSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Quantization != nil {
		in, out := &in.Quantization, &out.Quantization
		*out = new(QuantizationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Abliteration != nil {
		in, out := &in.Abliteration, &out.Abliteration
		*out = new(AbliterationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Finetune != nil {
		in, out := &in.Finetune, &out.Finetune
		*out = new(FinetuneSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(PublishSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Download != nil {
		in, out := &in.Download, &out.Download
		*out = new(DownloadSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheSpec.
func (in *ModelCacheSpec) DeepCopy() *ModelCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ModelCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheStatus) DeepCopyInto(out *ModelCacheStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAccessTime != nil {
		in, out := &in.LastAccessTime, &out.LastAccessTime
		*out = (*in).DeepCopy()
	}
	if in.ResidentSince != nil {
		in, out := &in.ResidentSince, &out.ResidentSince
		*out = (*in).DeepCopy()
	}
	if in.Quantization != nil {
		in, out := &in.Quantization, &out.Quantization
		*out = new(QuantizationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Abliteration != nil {
		in, out := &in.Abliteration, &out.Abliteration
		*out = new(AbliterationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Finetune != nil {
		in, out := &in.Finetune, &out.Finetune
		*out = new(FinetuneStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(PublishStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.OCIPulledAt != nil {
		in, out := &in.OCIPulledAt, &out.OCIPulledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheStatus.
func (in *ModelCacheStatus) DeepCopy() *ModelCacheStatus {
	if in == nil {
		return nil
	}
	out := new(ModelCacheStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDeployment) DeepCopyInto(out *ModelDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDeployment.
func (in *ModelDeployment) DeepCopy() *ModelDeployment {
	if in == nil {
		return nil
	}
	out := new(ModelDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDeploymentGPUGroupState) DeepCopyInto(out *ModelDeploymentGPUGroupState) {
	*out = *in
	if in.PreemptedAt != nil {
		in, out := &in.PreemptedAt, &out.PreemptedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDeploymentGPUGroupState.
func (in *ModelDeploymentGPUGroupState) DeepCopy() *ModelDeploymentGPUGroupState {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentGPUGroupState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDeploymentList) DeepCopyInto(out *ModelDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDeploymentList.
func (in *ModelDeploymentList) DeepCopy() *ModelDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDeploymentSpec) DeepCopyInto(out *ModelDeploymentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.IdleTimeoutSeconds != nil {
		in, out := &in.IdleTimeoutSeconds, &out.IdleTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.ColdStartTimeoutSeconds != nil {
		in, out := &in.ColdStartTimeoutSeconds, &out.ColdStartTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Benchmark != nil {
		in, out := &in.Benchmark, &out.Benchmark
		*out = new(BenchmarkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelCacheRef != nil {
		in, out := &in.ModelCacheRef, &out.ModelCacheRef
		*out = new(string)
		**out = **in
	}
	if in.LiteLLM != nil {
		in, out := &in.LiteLLM, &out.LiteLLM
		*out = new(LiteLLMSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MLCLLM != nil {
		in, out := &in.MLCLLM, &out.MLCLLM
		*out = new(MLCLLMSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VLLM != nil {
		in, out := &in.VLLM, &out.VLLM
		*out = new(VLLMSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LlamaCpp != nil {
		in, out := &in.LlamaCpp, &out.LlamaCpp
		*out = new(LlamaCppSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ComfyUI != nil {
		in, out := &in.ComfyUI, &out.ComfyUI
		*out = new(ComfyUISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VLLMOmni != nil {
		in, out := &in.VLLMOmni, &out.VLLMOmni
		*out = new(VLLMOmniSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GPUGroupRef != nil {
		in, out := &in.GPUGroupRef, &out.GPUGroupRef
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.VRAMEstimateMB != nil {
		in, out := &in.VRAMEstimateMB, &out.VRAMEstimateMB
		*out = new(int64)
		**out = **in
	}
	if in.ServiceLabels != nil {
		in, out := &in.ServiceLabels, &out.ServiceLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDeploymentSpec.
func (in *ModelDeploymentSpec) DeepCopy() *ModelDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDeploymentStatus) DeepCopyInto(out *ModelDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllocatedGPU != nil {
		in, out := &in.AllocatedGPU, &out.AllocatedGPU
		*out = new(GPUAllocation)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(ModelEndpoints)
		**out = **in
	}
	if in.LastAccessTime != nil {
		in, out := &in.LastAccessTime, &out.LastAccessTime
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(ModelMetrics)
		**out = **in
	}
	if in.GPUGroupState != nil {
		in, out := &in.GPUGroupState, &out.GPUGroupState
		*out = new(ModelDeploymentGPUGroupState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDeploymentStatus.
func (in *ModelDeploymentStatus) DeepCopy() *ModelDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpoints) DeepCopyInto(out *ModelEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpoints.
func (in *ModelEndpoints) DeepCopy() *ModelEndpoints {
	if in == nil {
		return nil
	}
	out := new(ModelEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMetrics) DeepCopyInto(out *ModelMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMetrics.
func (in *ModelMetrics) DeepCopy() *ModelMetrics {
	if in == nil {
		return nil
	}
	out := new(ModelMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreemptionResult) DeepCopyInto(out *PreemptionResult) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreemptionResult.
func (in *PreemptionResult) DeepCopy() *PreemptionResult {
	if in == nil {
		return nil
	}
	out := new(PreemptionResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishSpec) DeepCopyInto(out *PublishSpec) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]PublishTarget, len(*in))
		copy(*out, *in)
	}
	if in.OCIRef != nil {
		in, out := &in.OCIRef, &out.OCIRef
		*out = new(string)
		**out = **in
	}
	if in.HuggingFaceRepo != nil {
		in, out := &in.HuggingFaceRepo, &out.HuggingFaceRepo
		*out = new(string)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(string)
		**out = **in
	}
	if in.MaxMemoryGB != nil {
		in, out := &in.MaxMemoryGB, &out.MaxMemoryGB
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishSpec.
func (in *PublishSpec) DeepCopy() *PublishSpec {
	if in == nil {
		return nil
	}
	out := new(PublishSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishStatus) DeepCopyInto(out *PublishStatus) {
	*out = *in
	if in.PublishedAt != nil {
		in, out := &in.PublishedAt, &out.PublishedAt
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishStatus.
func (in *PublishStatus) DeepCopy() *PublishStatus {
	if in == nil {
		return nil
	}
	out := new(PublishStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantizationSpec) DeepCopyInto(out *QuantizationSpec) {
	*out = *in
	if in.Bits != nil {
		in, out := &in.Bits, &out.Bits
		*out = new(int32)
		**out = **in
	}
	if in.GroupSize != nil {
		in, out := &in.GroupSize, &out.GroupSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxMemoryGB != nil {
		in, out := &in.MaxMemoryGB, &out.MaxMemoryGB
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Sym != nil {
		in, out := &in.Sym, &out.Sym
		*out = new(bool)
		**out = **in
	}
	if in.DescAct != nil {
		in, out := &in.DescAct, &out.DescAct
		*out = new(bool)
		**out = **in
	}
	if in.Calibration != nil {
		in, out := &in.Calibration, &out.Calibration
		*out = new(CalibrationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GPUMemoryFraction != nil {
		in, out := &in.GPUMemoryFraction, &out.GPUMemoryFraction
		*out = new(string)
		**out = **in
	}
	if in.DynamicExclusion != nil {
		in, out := &in.DynamicExclusion, &out.DynamicExclusion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantizationSpec.
func (in *QuantizationSpec) DeepCopy() *QuantizationSpec {
	if in == nil {
		return nil
	}
	out := new(QuantizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantizationStatus) DeepCopyInto(out *QuantizationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.CalibrationParams != nil {
		in, out := &in.CalibrationParams, &out.CalibrationParams
		*out = new(CalibrationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantizationStatus.
func (in *QuantizationStatus) DeepCopy() *QuantizationStatus {
	if in == nil {
		return nil
	}
	out := new(QuantizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueSample) DeepCopyInto(out *QueueSample) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueSample.
func (in *QueueSample) DeepCopy() *QueueSample {
	if in == nil {
		return nil
	}
	out := new(QueueSample)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMOmniSpec) DeepCopyInto(out *VLLMOmniSpec) {
	*out = *in
	if in.GPUMemoryUtilization != nil {
		in, out := &in.GPUMemoryUtilization, &out.GPUMemoryUtilization
		*out = new(string)
		**out = **in
	}
	if in.MaxNumSeqs != nil {
		in, out := &in.MaxNumSeqs, &out.MaxNumSeqs
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMOmniSpec.
func (in *VLLMOmniSpec) DeepCopy() *VLLMOmniSpec {
	if in == nil {
		return nil
	}
	out := new(VLLMOmniSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMRopeScaling) DeepCopyInto(out *VLLMRopeScaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMRopeScaling.
func (in *VLLMRopeScaling) DeepCopy() *VLLMRopeScaling {
	if in == nil {
		return nil
	}
	out := new(VLLMRopeScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMSpec) DeepCopyInto(out *VLLMSpec) {
	*out = *in
	if in.TensorParallelSize != nil {
		in, out := &in.TensorParallelSize, &out.TensorParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxModelLen != nil {
		in, out := &in.MaxModelLen, &out.MaxModelLen
		*out = new(int32)
		**out = **in
	}
	if in.GPUMemoryUtilization != nil {
		in, out := &in.GPUMemoryUtilization, &out.GPUMemoryUtilization
		*out = new(string)
		**out = **in
	}
	if in.EnforceEager != nil {
		in, out := &in.EnforceEager, &out.EnforceEager
		*out = new(bool)
		**out = **in
	}
	if in.MaxNumSeqs != nil {
		in, out := &in.MaxNumSeqs, &out.MaxNumSeqs
		*out = new(int32)
		**out = **in
	}
	if in.SwapSpace != nil {
		in, out := &in.SwapSpace, &out.SwapSpace
		*out = new(int32)
		**out = **in
	}
	if in.TrustRemoteCode != nil {
		in, out := &in.TrustRemoteCode, &out.TrustRemoteCode
		*out = new(bool)
		**out = **in
	}
	if in.EnablePrefixCaching != nil {
		in, out := &in.EnablePrefixCaching, &out.EnablePrefixCaching
		*out = new(bool)
		**out = **in
	}
	if in.CalculateKVScales != nil {
		in, out := &in.CalculateKVScales, &out.CalculateKVScales
		*out = new(bool)
		**out = **in
	}
	if in.CPUOffloadGB != nil {
		in, out := &in.CPUOffloadGB, &out.CPUOffloadGB
		*out = new(int32)
		**out = **in
	}
	if in.EnableChunkedPrefill != nil {
		in, out := &in.EnableChunkedPrefill, &out.EnableChunkedPrefill
		*out = new(bool)
		**out = **in
	}
	if in.BlockSize != nil {
		in, out := &in.BlockSize, &out.BlockSize
		*out = new(int32)
		**out = **in
	}
	if in.RopeScaling != nil {
		in, out := &in.RopeScaling, &out.RopeScaling
		*out = new(VLLMRopeScaling)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMSpec.
func (in *VLLMSpec) DeepCopy() *VLLMSpec {
	if in == nil {
		return nil
	}
	out := new(VLLMSpec)
	in.DeepCopyInto(out)
	return out
}
