//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchmarkSpec) DeepCopyInto(out *BenchmarkSpec) {
	*out = *in
	if in.WarmupIterations != nil {
		in, out := &in.WarmupIterations, &out.WarmupIterations
		*out = new(int32)
		**out = **in
	}
	if in.MinDuration != nil {
		in, out := &in.MinDuration, &out.MinDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.Iterations != nil {
		in, out := &in.Iterations, &out.Iterations
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchmarkSpec.
func (in *BenchmarkSpec) DeepCopy() *BenchmarkSpec {
	if in == nil {
		return nil
	}
	out := new(BenchmarkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUAllocation) DeepCopyInto(out *GPUAllocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUAllocation.
func (in *GPUAllocation) DeepCopy() *GPUAllocation {
	if in == nil {
		return nil
	}
	out := new(GPUAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMSpec) DeepCopyInto(out *LiteLLMSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMSpec.
func (in *LiteLLMSpec) DeepCopy() *LiteLLMSpec {
	if in == nil {
		return nil
	}
	out := new(LiteLLMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaCppSpec) DeepCopyInto(out *LlamaCppSpec) {
	*out = *in
	if in.ContextSize != nil {
		in, out := &in.ContextSize, &out.ContextSize
		*out = new(int32)
		**out = **in
	}
	if in.NGPULayers != nil {
		in, out := &in.NGPULayers, &out.NGPULayers
		*out = new(int32)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.Threads != nil {
		in, out := &in.Threads, &out.Threads
		*out = new(int32)
		**out = **in
	}
	if in.FlashAttention != nil {
		in, out := &in.FlashAttention, &out.FlashAttention
		*out = new(bool)
		**out = **in
	}
	if in.MainGPU != nil {
		in, out := &in.MainGPU, &out.MainGPU
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaCppSpec.
func (in *LlamaCppSpec) DeepCopy() *LlamaCppSpec {
	if in == nil {
		return nil
	}
	out := new(LlamaCppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLCCompileOptions) DeepCopyInto(out *MLCCompileOptions) {
	*out = *in
	if in.UseCutlass != nil {
		in, out := &in.UseCutlass, &out.UseCutlass
		*out = new(bool)
		**out = **in
	}
	if in.UseFlashInfer != nil {
		in, out := &in.UseFlashInfer, &out.UseFlashInfer
		*out = new(bool)
		**out = **in
	}
	if in.UseCublasGemm != nil {
		in, out := &in.UseCublasGemm, &out.UseCublasGemm
		*out = new(bool)
		**out = **in
	}
	if in.UseCudaGraph != nil {
		in, out := &in.UseCudaGraph, &out.UseCudaGraph
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLCCompileOptions.
func (in *MLCCompileOptions) DeepCopy() *MLCCompileOptions {
	if in == nil {
		return nil
	}
	out := new(MLCCompileOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLCLLMSpec) DeepCopyInto(out *MLCLLMSpec) {
	*out = *in
	if in.GPUMemoryBytes != nil {
		in, out := &in.GPUMemoryBytes, &out.GPUMemoryBytes
		*out = new(int64)
		**out = **in
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(MLCOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.CompileOptions != nil {
		in, out := &in.CompileOptions, &out.CompileOptions
		*out = new(MLCCompileOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLCLLMSpec.
func (in *MLCLLMSpec) DeepCopy() *MLCLLMSpec {
	if in == nil {
		return nil
	}
	out := new(MLCLLMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLCOverrides) DeepCopyInto(out *MLCOverrides) {
	*out = *in
	if in.PrefillChunkSize != nil {
		in, out := &in.PrefillChunkSize, &out.PrefillChunkSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxTotalSeqLength != nil {
		in, out := &in.MaxTotalSeqLength, &out.MaxTotalSeqLength
		*out = new(int32)
		**out = **in
	}
	if in.ContextWindowSize != nil {
		in, out := &in.ContextWindowSize, &out.ContextWindowSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLCOverrides.
func (in *MLCOverrides) DeepCopy() *MLCOverrides {
	if in == nil {
		return nil
	}
	out := new(MLCOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCache) DeepCopyInto(out *ModelCache) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCache.
func (in *ModelCache) DeepCopy() *ModelCache {
	if in == nil {
		return nil
	}
	out := new(ModelCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelCache) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheList) DeepCopyInto(out *ModelCacheList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelCache, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheList.
func (in *ModelCacheList) DeepCopy() *ModelCacheList {
	if in == nil {
		return nil
	}
	out := new(ModelCacheList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelCacheList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheSpec) DeepCopyInto(out *ModelCacheSpec) {
	*out = *in
	if in.ClusterStorageClassName != nil {
		in, out := &in.ClusterStorageClassName, &out.ClusterStorageClassName
		*out = new(string)
		**out = **in
	}
	if in.ExistingClaimName != nil {
		in, out := &in.ExistingClaimName, &out.ExistingClaimName
		*out = new(string)
		**out = **in
	}
	if in.ModelPath != nil {
		in, out := &in.ModelPath, &out.ModelPath
		*out = new(string)
		**out = **in
	}
	if in.StorageSize != nil {
		in, out := &in.StorageSize, &out.StorageSize
		*out = new(string)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(string)
		**out = **in
	}
	if in.OCIRegistrySecretRef != nil {
		in, out := &in.OCIRegistrySecretRef, &out.OCIRegistrySecretRef
		*out = new(string)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HostPath != nil {
		in, out := &in.HostPath, &out.HostPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheSpec.
func (in *ModelCacheSpec) DeepCopy() *ModelCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ModelCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheStatus) DeepCopyInto(out *ModelCacheStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheStatus.
func (in *ModelCacheStatus) DeepCopy() *ModelCacheStatus {
	if in == nil {
		return nil
	}
	out := new(ModelCacheStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDeployment) DeepCopyInto(out *ModelDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDeployment.
func (in *ModelDeployment) DeepCopy() *ModelDeployment {
	if in == nil {
		return nil
	}
	out := new(ModelDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDeploymentList) DeepCopyInto(out *ModelDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDeploymentList.
func (in *ModelDeploymentList) DeepCopy() *ModelDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDeploymentSpec) DeepCopyInto(out *ModelDeploymentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.IdleTimeoutSeconds != nil {
		in, out := &in.IdleTimeoutSeconds, &out.IdleTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Benchmark != nil {
		in, out := &in.Benchmark, &out.Benchmark
		*out = new(BenchmarkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelCacheRef != nil {
		in, out := &in.ModelCacheRef, &out.ModelCacheRef
		*out = new(string)
		**out = **in
	}
	if in.LiteLLM != nil {
		in, out := &in.LiteLLM, &out.LiteLLM
		*out = new(LiteLLMSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MLCLLM != nil {
		in, out := &in.MLCLLM, &out.MLCLLM
		*out = new(MLCLLMSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VLLM != nil {
		in, out := &in.VLLM, &out.VLLM
		*out = new(VLLMSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LlamaCpp != nil {
		in, out := &in.LlamaCpp, &out.LlamaCpp
		*out = new(LlamaCppSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDeploymentSpec.
func (in *ModelDeploymentSpec) DeepCopy() *ModelDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDeploymentStatus) DeepCopyInto(out *ModelDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllocatedGPU != nil {
		in, out := &in.AllocatedGPU, &out.AllocatedGPU
		*out = new(GPUAllocation)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(ModelEndpoints)
		**out = **in
	}
	if in.LastAccessTime != nil {
		in, out := &in.LastAccessTime, &out.LastAccessTime
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(ModelMetrics)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDeploymentStatus.
func (in *ModelDeploymentStatus) DeepCopy() *ModelDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpoints) DeepCopyInto(out *ModelEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpoints.
func (in *ModelEndpoints) DeepCopy() *ModelEndpoints {
	if in == nil {
		return nil
	}
	out := new(ModelEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMetrics) DeepCopyInto(out *ModelMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMetrics.
func (in *ModelMetrics) DeepCopy() *ModelMetrics {
	if in == nil {
		return nil
	}
	out := new(ModelMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMSpec) DeepCopyInto(out *VLLMSpec) {
	*out = *in
	if in.TensorParallelSize != nil {
		in, out := &in.TensorParallelSize, &out.TensorParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxModelLen != nil {
		in, out := &in.MaxModelLen, &out.MaxModelLen
		*out = new(int32)
		**out = **in
	}
	if in.GPUMemoryUtilization != nil {
		in, out := &in.GPUMemoryUtilization, &out.GPUMemoryUtilization
		*out = new(string)
		**out = **in
	}
	if in.EnforceEager != nil {
		in, out := &in.EnforceEager, &out.EnforceEager
		*out = new(bool)
		**out = **in
	}
	if in.MaxNumSeqs != nil {
		in, out := &in.MaxNumSeqs, &out.MaxNumSeqs
		*out = new(int32)
		**out = **in
	}
	if in.SwapSpace != nil {
		in, out := &in.SwapSpace, &out.SwapSpace
		*out = new(int32)
		**out = **in
	}
	if in.TrustRemoteCode != nil {
		in, out := &in.TrustRemoteCode, &out.TrustRemoteCode
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMSpec.
func (in *VLLMSpec) DeepCopy() *VLLMSpec {
	if in == nil {
		return nil
	}
	out := new(VLLMSpec)
	in.DeepCopyInto(out)
	return out
}
