apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    component: mcp-server
  name: mcp-prometheus
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: prometheus
  type: ClusterIP
