apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
    component: mcp-server
  name: mcp-loki
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: loki
  type: ClusterIP
