apiVersion: v1
kind: Service
metadata:
  labels:
    app: memory
    component: mcp-server
  name: mcp-memory
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: memory
  type: ClusterIP
