// Package dockerfile generates Dockerfiles from environment fingerprints.
package dockerfile

import "text/template"

// goTemplate generates a Dockerfile for Go projects.
// When BaseImage is set (pre-built base), skips runtime and tool install layers.
var goTemplate = template.Must(template.New("go").Parse(`# Auto-generated by mcp-devbox — hash: {{ .Hash }}
{{ if .BaseImage -}}
FROM {{ .BaseImage }} AS base
ENV PATH="/usr/local/go/bin:${PATH}"
{{ range .SystemDeps }}RUN apk add --no-cache {{ . }}
{{ end -}}
{{ else -}}
FROM golang:{{ .GoVersion }}-alpine AS base
RUN apk add --no-cache ca-certificates git make bash curl{{ range .SystemDeps }} {{ . }}{{ end }}
{{ end -}}
WORKDIR /workspace

COPY go.mod go.sum* ./
RUN go mod download || true
{{ if not .BaseImage -}}
{{ range .Tools }}
RUN go install {{ . }}@latest
{{- end }}
{{ end -}}
{{ range .SetupCommands }}
RUN {{ . }}
{{- end }}
{{ range $k, $v := .Env }}
ENV {{ $k }}={{ $v }}
{{- end }}

CMD ["sleep", "infinity"]
`))

// pythonTemplate generates a Dockerfile for Python projects.
// When BaseImage is set (pre-built base), skips runtime and tool install layers.
var pythonTemplate = template.Must(template.New("python").Parse(`# Auto-generated by mcp-devbox — hash: {{ .Hash }}
{{ if .BaseImage -}}
FROM {{ .BaseImage }} AS base
{{ range .SystemDeps }}RUN apt-get update && apt-get install -y --no-install-recommends {{ . }} && rm -rf /var/lib/apt/lists/*
{{ end -}}
{{ else -}}
FROM python:{{ .PythonVersion }}-slim-bookworm AS base
RUN apt-get update && apt-get install -y --no-install-recommends \
    git make curl build-essential{{ range .SystemDeps }} {{ . }}{{ end }} \
    && rm -rf /var/lib/apt/lists/*
{{ if eq .DepManager "uv" }}RUN pip install --no-cache-dir uv{{ end }}
{{ if eq .DepManager "poetry" }}RUN pip install --no-cache-dir poetry{{ end }}
{{ end -}}
WORKDIR /workspace

{{ if eq .DepManager "uv" -}}
COPY pyproject.toml uv.lock* ./
RUN uv sync --frozen 2>/dev/null || uv sync || true
{{ else if eq .DepManager "poetry" -}}
COPY pyproject.toml poetry.lock* ./
RUN poetry install --no-interaction --no-root 2>/dev/null || true
{{ else -}}
COPY requirements.txt* ./
RUN pip install --no-cache-dir -r requirements.txt 2>/dev/null || true
{{ end -}}
{{ range .SetupCommands }}
RUN {{ . }}
{{- end }}
{{ range $k, $v := .Env }}
ENV {{ $k }}={{ $v }}
{{- end }}

CMD ["sleep", "infinity"]
`))

// nodeTemplate generates a Dockerfile for Node.js projects.
// When BaseImage is set (pre-built base), skips runtime and tool install layers.
var nodeTemplate = template.Must(template.New("node").Parse(`# Auto-generated by mcp-devbox — hash: {{ .Hash }}
{{ if .BaseImage -}}
FROM {{ .BaseImage }} AS base
{{ range .SystemDeps }}RUN apk add --no-cache {{ . }}
{{ end -}}
{{ else -}}
FROM node:{{ .NodeVersion }}-alpine AS base
RUN apk add --no-cache git make bash curl{{ range .SystemDeps }} {{ . }}{{ end }}
{{ if eq .DepManager "pnpm" }}RUN corepack enable && corepack prepare pnpm@latest --activate{{ end }}
{{ end -}}
WORKDIR /workspace

{{ if eq .DepManager "pnpm" -}}
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile 2>/dev/null || pnpm install || true
{{ else if eq .DepManager "yarn" -}}
COPY package.json yarn.lock* ./
RUN yarn install --frozen-lockfile 2>/dev/null || yarn install || true
{{ else -}}
COPY package.json package-lock.json* ./
RUN npm ci 2>/dev/null || npm install || true
{{ end -}}
{{ range .SetupCommands }}
RUN {{ . }}
{{- end }}
{{ range $k, $v := .Env }}
ENV {{ $k }}={{ $v }}
{{- end }}

CMD ["sleep", "infinity"]
`))

// rustTemplate generates a Dockerfile for Rust projects.
var rustTemplate = template.Must(template.New("rust").Parse(`# Auto-generated by mcp-devbox — hash: {{ .Hash }}
FROM rust:alpine AS base
RUN apk add --no-cache git make bash curl musl-dev{{ range .SystemDeps }} {{ . }}{{ end }}
WORKDIR /workspace

COPY Cargo.toml Cargo.lock* ./
RUN mkdir src && echo "fn main() {}" > src/main.rs && cargo fetch 2>/dev/null || true && rm -rf src
{{ range .SetupCommands }}
RUN {{ . }}
{{- end }}
{{ range $k, $v := .Env }}
ENV {{ $k }}={{ $v }}
{{- end }}

CMD ["sleep", "infinity"]
`))

// multiTemplate generates a Dockerfile for multi-language projects.
var multiTemplate = template.Must(template.New("multi").Parse(`# Auto-generated by mcp-devbox — hash: {{ .Hash }}
FROM {{ .BaseImage }} AS base
{{ if .GoBase }}ENV PATH="/usr/local/go/bin:${PATH}"
{{ end -}}
RUN {{ .PackageManager }} {{ .PackageInstallCmd }}{{ range .SystemDeps }} {{ . }}{{ end }}{{ if .ExtraPackageManagers }}{{ range .ExtraPackageManagers }}
RUN {{ . }}{{ end }}{{ end }}
WORKDIR /workspace
{{ range .DepSteps }}
{{ . }}
{{- end }}
{{ range .SetupCommands }}
RUN {{ . }}
{{- end }}
{{ range $k, $v := .Env }}
ENV {{ $k }}={{ $v }}
{{- end }}

CMD ["sleep", "infinity"]
`))
