// loom-hooks.ts - Loom lifecycle hooks for OpenCode
// Generated by: loom sync opencode --regen
// Provides session tracking, heartbeats, and presence management.

import type { Plugin } from "@opencode-ai/plugin"

export default (async ({ $, project }) => {
  const agentId = "opencode"
  const agentType = "opencode"
  const namespace = project?.name
    ? `${project.name}/main`
    : "opencode/main"

  // Helper: run loom CLI command, swallowing errors.
  const loom = async (...args: string[]) => {
    try {
      await $`loom ${args.join(" ")}`
    } catch {
      // Non-fatal: loom daemon may not be running.
    }
  }

  return {
    "session.created": async () => {
      await loom(
        "agent", "session-start",
        "--namespace", namespace,
        "--agent-id", agentId,
        "--agent-type", agentType,
        "--description", "OpenCode session",
        "--auto-recall",
        "--auto-recall-strategy", "fast",
        "--quiet"
      )
    },

    "session.deleted": async () => {
      await loom(
        "agent", "session-end",
        "--agent-id", agentId,
        "--summarize",
        "--summary-async",
        "--quiet"
      )
    },

    "session.idle": async () => {
      await loom(
        "agent", "heartbeat",
        "--agent-id", agentId,
        "--status", "active",
        "--ensure-session",
        "--agent-type", agentType,
        "--quiet"
      )
    },

    "tool.execute.after": async () => {
      await loom(
        "agent", "heartbeat",
        "--agent-id", agentId,
        "--status", "active",
        "--ensure-session",
        "--agent-type", agentType,
        "--quiet"
      )
    },
  }
}) satisfies Plugin
