apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
    component: mcp-server
  name: mcp-neo4j
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: neo4j
  type: ClusterIP
