// opencode.go contains OpenCode-specific hook generation.
//
// The MCP config generation for OpenCode is handled by the unified
// generateJSONConfig path (using profile.Features.CommandFormat == "array").
// This file only contains the TypeScript plugin generation for lifecycle hooks.
package generator

import (
	"os"
	"path/filepath"
)

// generateOpenCodeHooksPlugin writes a TypeScript plugin for OpenCode lifecycle hooks.
// The plugin provides session tracking, heartbeats, and presence management
// equivalent to Claude Code's shell-based hooks.
func generateOpenCodeHooksPlugin(outputDir string) error {
	destDir := filepath.Join(outputDir, "opencode", "plugins")
	if err := os.MkdirAll(destDir, 0755); err != nil {
		return err
	}

	pluginContent := `// loom-hooks.ts - Loom lifecycle hooks for OpenCode
// Generated by: loom sync opencode --regen
// Provides session tracking, heartbeats, and presence management.

import type { Plugin } from "@opencode-ai/plugin"

export default (async ({ $, project }) => {
  const agentId = "opencode"
  const agentType = "opencode"
  const namespace = project?.name
    ? ` + "`${project.name}/main`" + `
    : "opencode/main"

  // Helper: run loom CLI command, swallowing errors.
  const loom = async (...args: string[]) => {
    try {
      await $` + "`loom ${args.join(\" \")}`" + `
    } catch {
      // Non-fatal: loom daemon may not be running.
    }
  }

  return {
    "session.created": async () => {
      await loom(
        "agent", "session-start",
        "--namespace", namespace,
        "--agent-id", agentId,
        "--agent-type", agentType,
        "--description", "OpenCode session",
        "--auto-recall",
        "--auto-recall-strategy", "fast",
        "--quiet"
      )
    },

    "session.deleted": async () => {
      await loom(
        "agent", "session-end",
        "--agent-id", agentId,
        "--summarize",
        "--summary-async",
        "--quiet"
      )
    },

    "session.idle": async () => {
      await loom(
        "agent", "heartbeat",
        "--agent-id", agentId,
        "--status", "active",
        "--ensure-session",
        "--agent-type", agentType,
        "--quiet"
      )
    },

    "tool.execute.after": async () => {
      await loom(
        "agent", "heartbeat",
        "--agent-id", agentId,
        "--status", "active",
        "--ensure-session",
        "--agent-type", agentType,
        "--quiet"
      )
    },
  }
}) satisfies Plugin
`

	return os.WriteFile(filepath.Join(destDir, "loom-hooks.ts"), []byte(pluginContent), 0644)
}
