# Default values for flexinfer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

scheduler:
  weights:
    tps: 0.7
    util: 0.2
    cost: 0.1
