package clients

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/crb2nu/loom/pkg/mills/council"
	"github.com/crb2nu/loom/pkg/mills/eval"
)

// FlexInferCouncilReviewer adapts FlexInfer chat completions to the
// council.Reviewer contract. It is the production-safe local-tier reviewer:
// deterministic temperature, bounded output, and no frontier dependency.
type FlexInferCouncilReviewer struct {
	Client    *FlexInferClient
	MaxTokens int
}

// Review implements council.Reviewer.
func (r *FlexInferCouncilReviewer) Review(ctx context.Context, brief *council.Brief, lens council.ReviewerLens) (council.ReviewerOutput, error) {
	if r == nil || r.Client == nil {
		return council.ReviewerOutput{Lens: lens}, errors.New("flexinfer council reviewer: client not configured")
	}
	if brief == nil {
		return council.ReviewerOutput{Lens: lens}, errors.New("flexinfer council reviewer: brief required")
	}
	maxTokens := r.MaxTokens
	if maxTokens <= 0 {
		maxTokens = 2048
	}
	prompt := fmt.Sprintf(`You are the %q reviewer in the Loom Mills council.

Review the brief through this lens only. Return concise markdown with:
- material risks
- missing acceptance criteria
- concrete next slice recommendation
- any reason autonomy should fail closed

Brief:
%s`, lens.Name, brief.Markdown)
	out, cost, err := r.Client.Chat(ctx, lens.Model, prompt, maxTokens)
	if err != nil {
		return council.ReviewerOutput{Lens: lens}, err
	}
	return council.ReviewerOutput{
		Lens:     lens,
		Markdown: strings.TrimSpace(out),
		CostUSD:  cost,
	}, nil
}

// FlexInferCouncilEditor adapts FlexInfer chat completions to the
// council.Editor contract. It emits the three canonical council artifacts from
// one model response so the existing writer/mutator/eval flow stays unchanged.
type FlexInferCouncilEditor struct {
	Client    *FlexInferClient
	Backend   string
	Model     string
	MaxTokens int
}

// Edit implements council.Editor.
func (e *FlexInferCouncilEditor) Edit(ctx context.Context, brief *council.Brief, reviews []council.ReviewerOutput) (*council.EditorOutput, error) {
	if e == nil || e.Client == nil {
		return nil, errors.New("flexinfer council editor: client not configured")
	}
	if brief == nil {
		return nil, errors.New("flexinfer council editor: brief required")
	}
	maxTokens := e.MaxTokens
	if maxTokens <= 0 {
		maxTokens = 4096
	}
	prompt := buildCouncilEditorPrompt(brief, reviews)
	raw, cost, err := e.Client.Chat(ctx, e.Model, prompt, maxTokens)
	if err != nil {
		return nil, err
	}
	sections := splitCouncilSections(raw)
	models := councilModels(e.Model, reviews)
	return &council.EditorOutput{
		Backend: e.backend(),
		Model:   e.Model,
		CostUSD: cost,
		Documents: []council.ArtifactDoc{
			{Kind: council.KindResearch, Title: "Mills council research", Body: sections.research},
			{Kind: council.KindProductSpec, Title: "Mills council product spec", Body: sections.productSpec},
			{Kind: council.KindImplementation, Title: "Mills council implementation plan", Body: sections.implementation},
		},
		Sidecar: council.Sidecar{
			Models: models,
			CostUSD: council.SidecarCost{
				Local: cost + reviewCost(reviews),
			},
			BacklogDeltas: council.SidecarBacklog{},
			Notes:         "generated by FlexInfer-backed council participants",
		},
	}, nil
}

func (e *FlexInferCouncilEditor) backend() string {
	if strings.TrimSpace(e.Backend) != "" {
		return e.Backend
	}
	return "flexinfer"
}

func buildCouncilEditorPrompt(brief *council.Brief, reviews []council.ReviewerOutput) string {
	var b strings.Builder
	b.WriteString(`You are the Loom Mills council editor.

Synthesize the brief and reviewer notes into three markdown artifacts. Use these
exact top-level headings, in this order:

## Research
## Product Spec
## Implementation Plan

Keep the output implementation-ready and include machine-checkable success
criteria. Do not invent credentials or claim actions were completed.

Brief:
`)
	b.WriteString(brief.Markdown)
	if len(reviews) > 0 {
		b.WriteString("\n\nReviewer notes:\n")
	}
	for _, r := range reviews {
		fmt.Fprintf(&b, "\n### %s (%s/%s)\n%s\n",
			r.Lens.Name, r.Lens.Backend, r.Lens.Model, strings.TrimSpace(r.Markdown))
	}
	return b.String()
}

type councilSections struct {
	research       string
	productSpec    string
	implementation string
}

func splitCouncilSections(raw string) councilSections {
	raw = strings.TrimSpace(raw)
	sections := councilSections{
		research:       raw,
		productSpec:    "See research synthesis.",
		implementation: "See research synthesis.",
	}
	if raw == "" {
		sections.research = "No model output returned."
		return sections
	}

	type marker struct {
		key   string
		title string
		idx   int
	}
	markers := []marker{
		{key: "research", title: "## Research", idx: strings.Index(raw, "## Research")},
		{key: "product", title: "## Product Spec", idx: strings.Index(raw, "## Product Spec")},
		{key: "implementation", title: "## Implementation Plan", idx: strings.Index(raw, "## Implementation Plan")},
	}
	for _, m := range markers {
		if m.idx < 0 {
			return sections
		}
	}
	sort.Slice(markers, func(i, j int) bool { return markers[i].idx < markers[j].idx })
	values := map[string]string{}
	for i, m := range markers {
		start := m.idx + len(m.title)
		end := len(raw)
		if i+1 < len(markers) {
			end = markers[i+1].idx
		}
		values[m.key] = strings.TrimSpace(raw[start:end])
	}
	if values["research"] != "" {
		sections.research = values["research"]
	}
	if values["product"] != "" {
		sections.productSpec = values["product"]
	}
	if values["implementation"] != "" {
		sections.implementation = values["implementation"]
	}
	return sections
}

func councilModels(editorModel string, reviews []council.ReviewerOutput) []string {
	models := []string{}
	if editorModel != "" {
		models = append(models, editorModel)
	}
	for _, r := range reviews {
		if r.Lens.Model != "" {
			models = append(models, r.Lens.Model)
		}
	}
	sort.Strings(models)
	return models
}

func reviewCost(reviews []council.ReviewerOutput) float64 {
	var total float64
	for _, r := range reviews {
		total += r.CostUSD
	}
	return total
}

var _ council.Reviewer = (*FlexInferCouncilReviewer)(nil)
var _ council.Editor = (*FlexInferCouncilEditor)(nil)

// FlexInferEvalJudge adapts FlexInfer chat completions to eval.LLMJudge for
// the contradiction-free council criterion.
type FlexInferEvalJudge struct {
	Client    *FlexInferClient
	Model     string
	MaxTokens int
}

// JudgeContradiction implements eval.LLMJudge.
func (j *FlexInferEvalJudge) JudgeContradiction(ctx context.Context, in eval.Input) (float64, []string, error) {
	if j == nil || j.Client == nil {
		return 0, nil, errors.New("flexinfer eval judge: client not configured")
	}
	maxTokens := j.MaxTokens
	if maxTokens <= 0 {
		maxTokens = 1024
	}
	prompt := buildContradictionPrompt(in)
	raw, _, err := j.Client.Chat(ctx, j.Model, prompt, maxTokens)
	if err != nil {
		return 0, nil, err
	}
	score, findings, err := parseContradictionVerdict(raw)
	if err != nil {
		return 0, nil, err
	}
	return score, findings, nil
}

func buildContradictionPrompt(in eval.Input) string {
	var b strings.Builder
	b.WriteString(`Score whether this Mills council output contradicts recent state.

Return only JSON with:
{"score": <number 0..1 where 1 means no contradiction>, "findings": ["..."]}

Council sidecar:
`)
	if in.Sidecar != nil {
		if data, err := in.Sidecar.Marshal(); err == nil {
			b.Write(data)
		}
	}
	if in.EditorOutput != nil {
		b.WriteString("\n\nImplementation plan excerpt:\n")
		for _, d := range in.EditorOutput.Documents {
			if d.Kind == council.KindImplementation {
				b.WriteString(d.Body)
				break
			}
		}
	}
	return b.String()
}

func parseContradictionVerdict(raw string) (float64, []string, error) {
	raw = strings.TrimSpace(strings.Trim(raw, "`"))
	start := strings.Index(raw, "{")
	end := strings.LastIndex(raw, "}")
	if start >= 0 && end > start {
		raw = raw[start : end+1]
	}
	var payload struct {
		Score    float64  `json:"score"`
		Findings []string `json:"findings"`
	}
	if err := json.Unmarshal([]byte(raw), &payload); err != nil {
		return 0, nil, fmt.Errorf("parse contradiction verdict: %w; raw=%q", err, raw)
	}
	if payload.Score < 0 || payload.Score > 1 {
		return 0, nil, fmt.Errorf("contradiction score %.3f outside [0,1]", payload.Score)
	}
	return payload.Score, payload.Findings, nil
}

var _ eval.LLMJudge = (*FlexInferEvalJudge)(nil)
