apiVersion: v1
kind: Service
metadata:
  name: {{ include "flexinfer.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flexinfer.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  selector:
    {{- include "flexinfer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
  ports:
    - port: 8082
      targetPort: http
      protocol: TCP
      name: http
