apiVersion: v1
kind: Service
metadata:
  labels:
    app: substack
    component: mcp-server
  name: mcp-substack
spec:
  ports:
    - name: websocket
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: substack
  type: ClusterIP
