name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Set up envtest
      uses: sigs.k8s.io/controller-runtime/tools/setup-envtest@v0
      with:
        version: '0.16.3'
    - name: Run tests
      run: go test ./...