name: Seed issues from YAML
run-name: Seed issues (${{ github.event.inputs.preview == 'true' && 'dry-run' || 'live' }})

on:
  workflow_dispatch:
    inputs:
      preview:
        description: "Set to 'true' for a dry-run"
        required: false
        default: "false"

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Tidy Go modules
        run: go mod tidy

      - name: Run issue seeder
        env:
          # The PAT is required for project board access
          GH_TOKEN: ${{ secrets.GH_PAT }}
          DRY_RUN: ${{ github.event.inputs.preview }}
        run: |
          go run ./hack/seed-issues.go
