name: Seed issues from YAML
run-name: Seed issues (${{ github.event.inputs.preview == 'true' && 'dry-run' || 'live' }})

on:
  workflow_dispatch:
    inputs:
      preview:
        description: "Set to 'true' for a dry-run"
        required: false
        default: "false"

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Tidy Go modules
        run: go mod tidy

      - name: Authenticate and Find Project ID
        id: project
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "1. Verifying authentication..."
          gh auth status -t

          echo "2. Finding project ID for project #1..."
          PROJECT_ID=$(gh project list --owner flexinfer --format json | jq -r '.projects[] | select(.number == 1) | .id')
          
          if [ -z "$PROJECT_ID" ]; then
            echo "Error: Could not find project #1 for organization 'flexinfer'."
            exit 1
          fi
          
          echo "Found project ID: $PROJECT_ID"
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_OUTPUT

      - name: Run issue seeder
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          DRY_RUN: ${{ github.event.inputs.preview }}
        run: |
          go run ./hack/seed-issues.go ${{ steps.project.outputs.PROJECT_ID }}