package main

import "gitlab.flexinfer.ai/libs/mcp-go"

func registerWorkflowCRMTools(server *mcp.Server, s *jobsearchServer) {
	specs := []endpointToolSpec{
		{
			Name:         "jobsearch_entities_list",
			Description:  "List entities",
			Method:       httpMethodGet,
			PathTemplate: "/entities",
			AllowQuery:   true,
		},
		{
			Name:         "jobsearch_entities_get",
			Description:  "Get an entity by id",
			Method:       httpMethodGet,
			PathTemplate: "/entities/{entity_id}",
			PathArgs:     []string{"entity_id"},
		},
		{
			Name:           "jobsearch_entities_create",
			Description:    "Create an entity",
			Method:         httpMethodPost,
			PathTemplate:   "/entities",
			RequirePayload: true,
		},
		{
			Name:           "jobsearch_entities_update",
			Description:    "Update an entity",
			Method:         httpMethodPut,
			PathTemplate:   "/entities/{entity_id}",
			PathArgs:       []string{"entity_id"},
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_entities_delete",
			Description:  "Delete an entity (requires confirm=true)",
			Method:       httpMethodDelete,
			PathTemplate: "/entities/{entity_id}",
			PathArgs:     []string{"entity_id"},
			ConfirmField: "confirm",
		},
		{
			Name:           "jobsearch_entities_search",
			Description:    "Search entities",
			Method:         httpMethodPost,
			PathTemplate:   "/entities/search",
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_entity_relations_list",
			Description:  "List relations for an entity",
			Method:       httpMethodGet,
			PathTemplate: "/entities/{entity_id}/relations",
			PathArgs:     []string{"entity_id"},
			AllowQuery:   true,
		},
		{
			Name:           "jobsearch_entity_relations_create",
			Description:    "Create a relation for an entity",
			Method:         httpMethodPost,
			PathTemplate:   "/entities/{entity_id}/relations",
			PathArgs:       []string{"entity_id"},
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_entity_relations_delete",
			Description:  "Delete an entity relation (requires confirm=true)",
			Method:       httpMethodDelete,
			PathTemplate: "/entities/{entity_id}/relations/{relation_id}",
			PathArgs:     []string{"entity_id", "relation_id"},
			ConfirmField: "confirm",
		},
		{
			Name:           "jobsearch_entity_status_transition",
			Description:    "Transition entity status",
			Method:         httpMethodPost,
			PathTemplate:   "/entities/{entity_id}/status",
			PathArgs:       []string{"entity_id"},
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_leads_list",
			Description:  "List leads",
			Method:       httpMethodGet,
			PathTemplate: "/leads",
			AllowQuery:   true,
		},
		{
			Name:         "jobsearch_leads_get",
			Description:  "Get lead by id",
			Method:       httpMethodGet,
			PathTemplate: "/leads/{lead_id}",
			PathArgs:     []string{"lead_id"},
		},
		{
			Name:           "jobsearch_leads_create",
			Description:    "Create a lead",
			Method:         httpMethodPost,
			PathTemplate:   "/leads",
			RequirePayload: true,
		},
		{
			Name:           "jobsearch_leads_update",
			Description:    "Update a lead",
			Method:         httpMethodPut,
			PathTemplate:   "/leads/{lead_id}",
			PathArgs:       []string{"lead_id"},
			RequirePayload: true,
		},
		{
			Name:           "jobsearch_leads_ingest",
			Description:    "Ingest a lead",
			Method:         httpMethodPost,
			PathTemplate:   "/leads/ingest",
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_workflow_today",
			Description:  "Get workflow today summary",
			Method:       httpMethodGet,
			PathTemplate: "/workflow/today",
		},
		{
			Name:         "jobsearch_workflow_followups",
			Description:  "Get workflow follow-ups",
			Method:       httpMethodGet,
			PathTemplate: "/workflow/follow-ups",
		},
		{
			Name:         "jobsearch_workflow_drafts_list",
			Description:  "List workflow drafts",
			Method:       httpMethodGet,
			PathTemplate: "/workflow/drafts",
			AllowQuery:   true,
		},
		{
			Name:           "jobsearch_workflow_drafts_create",
			Description:    "Create a workflow draft",
			Method:         httpMethodPost,
			PathTemplate:   "/workflow/drafts",
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_workflow_drafts_send",
			Description:  "Send a workflow draft",
			Method:       httpMethodPost,
			PathTemplate: "/workflow/drafts/{draft_id}/send",
			PathArgs:     []string{"draft_id"},
			AllowPayload: true,
		},
		{
			Name:         "jobsearch_workflow_drafts_delete",
			Description:  "Delete a workflow draft (requires confirm=true)",
			Method:       httpMethodDelete,
			PathTemplate: "/workflow/drafts/{draft_id}",
			PathArgs:     []string{"draft_id"},
			ConfirmField: "confirm",
		},
		{
			Name:         "jobsearch_sources_list",
			Description:  "List job sources",
			Method:       httpMethodGet,
			PathTemplate: "/sources",
			AllowQuery:   true,
		},
		{
			Name:         "jobsearch_source_sync",
			Description:  "Sync a source",
			Method:       httpMethodPost,
			PathTemplate: "/sources/{source_id}/sync",
			PathArgs:     []string{"source_id"},
			AllowPayload: true,
		},
		{
			Name:         "jobsearch_integrations_list",
			Description:  "List integrations",
			Method:       httpMethodGet,
			PathTemplate: "/integrations",
			AllowQuery:   true,
		},
		{
			Name:         "jobsearch_integration_sync",
			Description:  "Sync an integration",
			Method:       httpMethodPost,
			PathTemplate: "/integrations/{integration_id}/sync",
			PathArgs:     []string{"integration_id"},
			AllowPayload: true,
		},
		{
			Name:         "jobsearch_feed_list",
			Description:  "List feed items",
			Method:       httpMethodGet,
			PathTemplate: "/feed",
			AllowQuery:   true,
		},
		{
			Name:         "jobsearch_feed_refresh",
			Description:  "Refresh feed",
			Method:       httpMethodPost,
			PathTemplate: "/feed/refresh",
			AllowPayload: true,
		},
		{
			Name:         "jobsearch_jobs_list",
			Description:  "List background jobs",
			Method:       httpMethodGet,
			PathTemplate: "/jobs",
			AllowQuery:   true,
		},
		{
			Name:         "jobsearch_job_cancel",
			Description:  "Cancel a background job (requires confirm=true)",
			Method:       httpMethodDelete,
			PathTemplate: "/jobs/{job_id}",
			PathArgs:     []string{"job_id"},
			ConfirmField: "confirm",
		},
		{
			Name:           "jobsearch_search_semantic",
			Description:    "Run semantic search",
			Method:         httpMethodPost,
			PathTemplate:   "/search/semantic",
			RequirePayload: true,
		},
	}

	for _, spec := range specs {
		s.addEndpointTool(server, spec)
	}
}
