package main

import "gitlab.flexinfer.ai/libs/mcp-go"

func registerResumeTools(server *mcp.Server, s *jobsearchServer) {
	for _, spec := range resumeEndpointToolSpecs() {
		s.addEndpointTool(server, spec)
	}
}

func resumeEndpointToolSpecs() []endpointToolSpec {
	return []endpointToolSpec{
		{
			Name:           "jobsearch_entities_compose_resume",
			Description:    "Compose and persist a tailored resume variant for an entity",
			Method:         httpMethodPost,
			PathTemplate:   "/entities/{entity_id}/compose-resume",
			PathArgs:       []string{"entity_id"},
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_resumes_data_get",
			Description:  "Get source resume-data YAML model projection",
			Method:       httpMethodGet,
			PathTemplate: "/resumes/data",
		},
		{
			Name:           "jobsearch_resumes_compose",
			Description:    "Compose resume content from a job description",
			Method:         httpMethodPost,
			PathTemplate:   "/resumes/compose",
			RequirePayload: true,
		},
		{
			Name:           "jobsearch_resumes_compose_save",
			Description:    "Save composed resume content as a generated variant",
			Method:         httpMethodPost,
			PathTemplate:   "/resumes/compose/save",
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_resumes_preview",
			Description:  "Preview ad-hoc resume HTML for supplied refs",
			Method:       httpMethodGet,
			PathTemplate: "/resumes/preview",
			AllowQuery:   true,
		},
		{
			Name:         "jobsearch_resumes_variant_markdown",
			Description:  "Render a named YAML-backed variant as Markdown",
			Method:       httpMethodGet,
			PathTemplate: "/resumes/{variant}/markdown",
			PathArgs:     []string{"variant"},
		},
		{
			Name:         "jobsearch_resumes_variant_html",
			Description:  "Render a named YAML-backed variant as HTML",
			Method:       httpMethodGet,
			PathTemplate: "/resumes/{variant}/html",
			PathArgs:     []string{"variant"},
		},
		{
			Name:           "jobsearch_resumes_variant_save",
			Description:    "Create or update a named YAML-backed resume variant",
			Method:         httpMethodPut,
			PathTemplate:   "/resumes/variants/{name}",
			PathArgs:       []string{"name"},
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_resumes_variant_delete",
			Description:  "Delete a named YAML-backed resume variant (requires confirm=true)",
			Method:       httpMethodDelete,
			PathTemplate: "/resumes/variants/{name}",
			PathArgs:     []string{"name"},
			ConfirmField: "confirm",
		},
		{
			Name:         "jobsearch_resumes_db_init",
			Description:  "Initialize DB resume state from YAML",
			Method:       httpMethodPost,
			PathTemplate: "/resumes/db/init",
		},
		{
			Name:         "jobsearch_resumes_db_get",
			Description:  "Get DB-backed resume with variants",
			Method:       httpMethodGet,
			PathTemplate: "/resumes/db",
		},
		{
			Name:         "jobsearch_resumes_db_sync",
			Description:  "Sync DB-backed resume state back to YAML",
			Method:       httpMethodPost,
			PathTemplate: "/resumes/db/sync",
		},
		{
			Name:         "jobsearch_resumes_db_variant_get",
			Description:  "Get DB-backed resume variant by id",
			Method:       httpMethodGet,
			PathTemplate: "/resumes/db/variants/{variant_id}",
			PathArgs:     []string{"variant_id"},
		},
		{
			Name:         "jobsearch_resumes_db_variant_html",
			Description:  "Render DB-backed resume variant HTML by id",
			Method:       httpMethodGet,
			PathTemplate: "/resumes/db/variants/{variant_id}/html",
			PathArgs:     []string{"variant_id"},
		},
		{
			Name:         "jobsearch_resumes_db_variant_delete",
			Description:  "Delete DB-backed resume variant by id (requires confirm=true)",
			Method:       httpMethodDelete,
			PathTemplate: "/resumes/db/variants/{variant_id}",
			PathArgs:     []string{"variant_id"},
			ConfirmField: "confirm",
		},
		{
			Name:         "jobsearch_resumes_versions_list",
			Description:  "List resume versions",
			Method:       httpMethodGet,
			PathTemplate: "/resumes/versions",
		},
		{
			Name:         "jobsearch_resumes_versions_get",
			Description:  "Get resume version detail by id",
			Method:       httpMethodGet,
			PathTemplate: "/resumes/versions/{version_id}",
			PathArgs:     []string{"version_id"},
		},
		{
			Name:         "jobsearch_resumes_versions_create",
			Description:  "Create a new resume version snapshot",
			Method:       httpMethodPost,
			PathTemplate: "/resumes/versions",
			AllowPayload: true,
		},
		{
			Name:         "jobsearch_resumes_versions_restore",
			Description:  "Restore resume from a version id",
			Method:       httpMethodPost,
			PathTemplate: "/resumes/versions/{version_id}/restore",
			PathArgs:     []string{"version_id"},
			AllowPayload: true,
		},
		{
			Name:         "jobsearch_resume_chat_sessions_list",
			Description:  "List active resume chat sessions",
			Method:       httpMethodGet,
			PathTemplate: "/chat/resume/sessions",
		},
		{
			Name:         "jobsearch_resume_chat_sessions_start",
			Description:  "Start a resume chat session",
			Method:       httpMethodPost,
			PathTemplate: "/chat/resume/sessions",
			AllowPayload: true,
		},
		{
			Name:         "jobsearch_resume_chat_session_get",
			Description:  "Get a resume chat session state",
			Method:       httpMethodGet,
			PathTemplate: "/chat/resume/sessions/{session_id}",
			PathArgs:     []string{"session_id"},
		},
		{
			Name:         "jobsearch_resume_chat_session_end",
			Description:  "End a resume chat session (requires confirm=true)",
			Method:       httpMethodDelete,
			PathTemplate: "/chat/resume/sessions/{session_id}",
			PathArgs:     []string{"session_id"},
			ConfirmField: "confirm",
		},
		{
			Name:           "jobsearch_resume_chat_message_send",
			Description:    "Send a message to a resume chat session",
			Method:         httpMethodPost,
			PathTemplate:   "/chat/resume/sessions/{session_id}/messages",
			PathArgs:       []string{"session_id"},
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_resume_chat_apply",
			Description:  "Apply pending resume chat operations",
			Method:       httpMethodPost,
			PathTemplate: "/chat/resume/sessions/{session_id}/apply",
			PathArgs:     []string{"session_id"},
			AllowPayload: true,
		},
		{
			Name:         "jobsearch_resume_chat_undo",
			Description:  "Undo most recent resume chat operation",
			Method:       httpMethodPost,
			PathTemplate: "/chat/resume/sessions/{session_id}/undo",
			PathArgs:     []string{"session_id"},
			AllowPayload: true,
		},
		{
			Name:         "jobsearch_resume_chat_redo",
			Description:  "Redo most recently undone resume chat operation",
			Method:       httpMethodPost,
			PathTemplate: "/chat/resume/sessions/{session_id}/redo",
			PathArgs:     []string{"session_id"},
			AllowPayload: true,
		},
		{
			Name:           "jobsearch_resume_chat_save_variant",
			Description:    "Persist resume chat session state as a named variant",
			Method:         httpMethodPost,
			PathTemplate:   "/chat/resume/sessions/{session_id}/save",
			PathArgs:       []string{"session_id"},
			RequirePayload: true,
		},
		{
			Name:         "jobsearch_resume_chat_preview",
			Description:  "Preview current resume chat session variant",
			Method:       httpMethodGet,
			PathTemplate: "/chat/resume/sessions/{session_id}/preview",
			PathArgs:     []string{"session_id"},
		},
		{
			Name:         "jobsearch_resume_chat_options",
			Description:  "Get available options for resume chat session",
			Method:       httpMethodGet,
			PathTemplate: "/chat/resume/sessions/{session_id}/options",
			PathArgs:     []string{"session_id"},
		},
	}
}
